### ISSUE TITLE
Instructions in the README are lacking some details

### ISSUE THREAD

**Issue by tttppp** [spamguy/vue-dipl.io#2]
I had a go at starting this project today, hoping to find out how it works.  The first thing I found is  that `npm run dev` doesn't work.  I don't think this is implemented, as there's nothing in package.json about `dev`.

After that I tried building it locally with `npm run build` and starting it with `serve -s dist`. I got to the login page, which failed since my local server doesn't have permission to get a token from google authentication.

Next I found that there were some references to "fake-id", so I tried accessing http://localhost:5000/?fake-id=a instead. Now logging in "works", but I see no games - even if I set up a local Diplicity server and create some games.  Is there a different URI I should be going to?  Perhaps my local diplicity server should be on a different port than 8080?

I know this project isn't fully functional, but I wanted to see where it's up to, and if I can help at all.

**Comment by spamguy** [comment]
Hey there @tttppp. Doing great stuff as always.

I agree the docs are limited and probably not even accurate. If you ping me on the Diplicity Slack channel—I'm on all the time, even though no one's there—I can get you going ASAP.

You won't see any games after a successful setup because the dev environment of diplicity starts a new database from scratch. With some config file tinkering you could plug into the production database, but the risk of damaging live data makes this unwise.

I would be overjoyed to collaborate on this if you have the interest and energy. My day job consumes most of my desire to write code, but I would easily find motivation again if other people show interest. dipl.io v1 is showing its age (always has from Day 1, TBH) and needs a proper upgrade.

**Comment by tttppp** [comment]
Hi spamguy! I'm not on the Slack channel, so I wonder if you could either invite me or let me know how to add myself. I started a thread in the Google dev group about Slack. Alternatively I'm already on the diplomacy Nexus Discord server, which there's a link to from the main Google Groups page.

**Comment by spamguy** [comment]
Hi again. I hunted you down on Discord rather than bring you into the Slack channel—the place is dead, really. You're not missing anything.

**Comment by spamguy** [comment]
Instructions updated. Closing.

**Comment by tttppp** [comment]
Thank you!
